import { StyleSheet } from "react-native";

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#f9f9f9",
      },
      header: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        backgroundColor: "#c41e3a",
        paddingVertical: 16,
        paddingHorizontal: 20,
        elevation: 4,
      },
      headerTitle: {
        fontSize: 20,
        fontWeight: "bold",
        color: "#fff",
      },
      filterButton: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "rgba(255, 255, 255, 0.2)",
        paddingVertical: 8,
        paddingHorizontal: 12,
        borderRadius: 20,
      },
      filterButtonText: {
        color: "#fff",
        marginLeft: 4,
        fontWeight: "500",
      },
      activeFiltersContainer: {
        paddingVertical: 10,
        paddingHorizontal: 15,
        backgroundColor: "#fff",
        borderBottomWidth: 1,
        borderBottomColor: "#eee",
      },
      activeFilterTag: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#c41e3a",
        paddingVertical: 6,
        paddingHorizontal: 12,
        borderRadius: 16,
        marginRight: 8,
      },
      activeFilterText: {
        color: "#fff",
        marginRight: 6,
        fontSize: 12,
      },
      clearFiltersButton: {
        backgroundColor: "#333",
        paddingVertical: 6,
        paddingHorizontal: 12,
        borderRadius: 16,
        marginRight: 8,
      },
      clearFiltersText: {
        color: "#fff",
        fontSize: 12,
      },
      modalOverlay: {
        flex: 1,
        backgroundColor: "rgba(0, 0, 0, 0.5)",
        justifyContent: "flex-end",
      },
      modalContent: {
        backgroundColor: "#fff",
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        height: "80%",
      },
      modalHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        padding: 20,
        borderBottomWidth: 1,
        borderBottomColor: "#eee",
      },
      modalTitle: {
        fontSize: 18,
        fontWeight: "bold",
        color: "#c41e3a",
      },
      modalBody: {
        padding: 20,
      },
      filterSectionTitle: {
        fontSize: 16,
        fontWeight: "bold",
        marginBottom: 10,
        marginTop: 15,
        color: "#333",
      },
      statusFiltersContainer: {
        flexDirection: "row",
        flexWrap: "wrap",
        marginBottom: 10,
      },
      statusFilterOption: {
        paddingVertical: 8,
        paddingHorizontal: 16,
        borderRadius: 20,
        borderWidth: 1,
        borderColor: "#ddd",
        marginRight: 10,
        marginBottom: 10,
      },
      selectedStatusFilter: {
        backgroundColor: "#c41e3a",
        borderColor: "#c41e3a",
      },
      statusFilterText: {
        color: "#333",
      },
      selectedStatusFilterText: {
        color: "#fff",
      },
      searchContainer: {
        flexDirection: "row",
        marginBottom: 15,
      },
      searchInput: {
        flex: 1,
        borderWidth: 1,
        borderColor: "#ddd",
        borderRadius: 8,
        paddingHorizontal: 12,
        paddingVertical: 8,
        marginRight: 10,
      },
      searchButton: {
        backgroundColor: "#c41e3a",
        paddingVertical: 10,
        paddingHorizontal: 15,
        borderRadius: 8,
        justifyContent: "center",
      },
      searchButtonText: {
        color: "#fff",
        fontWeight: "500",
      },
      switchContainer: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 15,
      },
      switchLabel: {
        fontSize: 14,
        color: "#333",
      },
      modalActions: {
        flexDirection: "row",
        justifyContent: "space-between",
        marginTop: 20,
        marginBottom: 30,
      },
      clearButton: {
        flex: 1,
        paddingVertical: 12,
        borderWidth: 1,
        borderColor: "#c41e3a",
        borderRadius: 8,
        marginRight: 10,
        alignItems: "center",
      },
      clearButtonText: {
        color: "#c41e3a",
        fontWeight: "500",
      },
      applyButton: {
        flex: 1,
        paddingVertical: 12,
        backgroundColor: "#c41e3a",
        borderRadius: 8,
        alignItems: "center",
      },
      applyButtonText: {
        color: "#fff",
        fontWeight: "500",
      },
      loadingContainer: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
      },
      loadingText: {
        marginTop: 10,
        color: "#c41e3a",
        fontSize: 16,
      },
      bookingsContainer: {
        padding: 15,
      },
      card: {
        backgroundColor: "#fff",
        borderRadius: 12,
        marginBottom: 16,
        padding: 16,
        elevation: 3,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
      },
      cardHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 12,
      },
      bookingIdContainer: {
        flexDirection: "row",
        alignItems: "center",
      },
      bookingId: {
        fontSize: 16,
        fontWeight: "bold",
        marginLeft: 6,
        color: "#333",
      },
      statusBadge: {
        paddingVertical: 4,
        paddingHorizontal: 10,
        borderRadius: 12,
      },
      statusText: {
        color: "#fff",
        fontSize: 12,
        fontWeight: "500",
      },
      cardDivider: {
        height: 1,
        backgroundColor: "#eee",
        marginVertical: 12,
      },
      guestInfoContainer: {
        marginBottom: 12,
      },
      infoRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        gap:14,
        marginBottom: 12,
      },
      infoItem: {
        flexDirection: "row",
        alignItems: "center",
        flex: 1,
      },
      infoLabel: {
        fontSize: 12,
        color: "#666",
        marginLeft: 4,
        marginRight: 4,
      },
      infoValue: {
        marginLeft:4,
        fontSize: 14,
        color: "#333",
        fontWeight: "500",
      },
      paymentStatusContainer: {
        alignItems: "flex-end",
        marginTop: 4,
      },
      paymentStatusText: {
        fontSize: 13,
        fontWeight: "500",
      },
      cardActions: {
        marginTop: 12,
        alignItems: "center",
      },
      checkInButton: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "#c41e3a",
        paddingVertical: 10,
        paddingHorizontal: 20,
        borderRadius: 8,
        width: "100%",
      },
      checkOutButton: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "#e74c3c",
        paddingVertical: 10,
        paddingHorizontal: 20,
        borderRadius: 8,
        width: "100%",
      },
      buttonText: {
        color: "#fff",
        fontWeight: "bold",
        marginLeft: 6,
      },
      completedContainer: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        paddingVertical: 10,
      },
      completedText: {
        color: "#4CAF50",
        fontWeight: "500",
        marginLeft: 6,
      },
      emptyContainer: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        padding: 20,
      },
      noDataText: {
        fontSize: 18,
        fontWeight: "bold",
        color: "#c41e3a",
        marginTop: 16,
      },
      noDataSubText: {
        fontSize: 14,
        color: "#666",
        marginTop: 8,
      },
      resetFiltersButton: {
        marginTop: 20,
        paddingVertical: 10,
        paddingHorizontal: 20,
        backgroundColor: "#c41e3a",
        borderRadius: 8,
      },
      resetFiltersText: {
        color: "#fff",
        fontWeight: "500",
      },
});
